# Camadas de Convolução
MIN_CAMADAS_CONV = 1
MAX_CAMADAS_CONV = 2

# Camadas Densas
MIN_CAMADAS_DENSE = 1
MAX_CAMADAS_DENSE = 2

# Neurônios Densos
MIN_NEURONIOS_DENSE = 64
MAX_NEURONIOS_DENSE = 256

# Dropout
MIN_DROPOUT = 0.1
MAX_DROPOUT = 0.5

# Regularização L2
MIN_L2 = 0.01
MAX_L2 = 0.1

# Opções de Batch Size
OPCOES_BATCH_SIZE = 32

# Épocas
MIN_EPOCHS = 5
MAX_EPOCHS = 25

# Número de Camadas
MIN_NUM_CAMADAS = 1
MAX_NUM_CAMADAS = 3

# Número de Neurônios
MIN_NUM_NEURONIOS = 10
MAX_NUM_NEURONIOS = 100

# Total de Neurônios
MIN_TOTAL_NEURONIOS = 10
MAX_TOTAL_NEURONIOS = 100

# Taxa de Aprendizado
MIN_TAXA_APRENDIZADO = 0.0001
MAX_TAXA_APRENDIZADO = 0.1

# Momento
MIN_MOMENTO = 0.9
MAX_MOMENTO = 0.99

# Função de Ativação
OPCOES_FUNCAO_ATIVACAO = ['relu', 'tanh', 'sigmoid']

# Taxa de Mutação
MIN_TAXA_MUTACAO = 0.01
MAX_TAXA_MUTACAO = 0.1

# Número de Camadas de Convolução
MIN_NUM_CAMADAS_CONV = 1
MAX_NUM_CAMADAS_CONV = 5
OPCOES_NUM_CAMADAS_CONV = None

# Número de Camadas Densas
MIN_NUM_CAMADAS_DENSE = 1
MAX_NUM_CAMADAS_DENSE = 5
OPCOES_NUM_CAMADAS_DENSE = None

# Número de Neurônios Densos
MIN_NUM_NEURONIOS_DENSE = 1
MAX_NUM_NEURONIOS_DENSE = 1000
OPCOES_NUM_NEURONIOS_DENSE = None

# Valor de Dropout
MIN_VALOR_DROPOUT = 0.0
MAX_VALOR_DROPOUT = 0.5
OPCOES_VALOR_DROPOUT = None

# Valor de Regularização L2
MIN_VALOR_L2 = 0.01
MAX_VALOR_L2 = 0.1
OPCOES_VALOR_L2 = None

# Tamanho do Batch
MIN_TAMANHO_BATCH = 32
MAX_TAMANHO_BATCH = 64
OPCOES_TAMANHO_BATCH = None

# Número de Épocas
MIN_NUM_EPOCHS = 5
MAX_NUM_EPOCHS = 25
OPCOES_NUM_EPOCHS = None

# Total de Camadas
MIN_TOTAL_CAMADAS = 1
MAX_TOTAL_CAMADAS = 5
OPCOES_TOTAL_CAMADAS = None

# Valor de Momento
MIN_VALOR_MOMENTO = 0.9
MAX_VALOR_MOMENTO = 0.99
OPCOES_VALOR_MOMENTO = None
